### PR TITLE
32 add spatial audio framework submodule and integrate into build system

### PR DESCRIPTION
**Pull request by liam-strand**

### CODE REVIEW

**Review by thompson-tyler — APPROVED** [review]
Build system looks awesome! I haven't looked at `build.rs` this closely before so it was fun to read about and figure out what you're doing. Ran great on my machine too... really really good work. As a sanity check for myself I hunted down the generated bindings and compare them to the actual SAF bindings, I figure others will find the comparison interesting too:

_A random header from the SAF library:_
image
_...and the corresponding header generated by bindgen:_
image

**Comment by liam-strand** [comment]
Ok so I'm wondering why the C api has `void *const hBin` and the rust api has `hBin: *mut c_void`. I would expect it to be `hBin: *const c_void`. I'm not going to question lord bindgen here but just curious.

**Comment by aydabee** [comment]
Screenshot 2023-11-25 at 11 10 01 PM

I haven't taken a super in-depth look yet, nor have I tried to debug this yet, but not currently running on my machine. Will look further into it when I have more time, but dropping a screenshot in case it's a simple fix that someone has already seen!

**Comment by liam-strand** [comment]
Ah yes when you clone the repo you have to recurse submodules now to get the SAF code. Sorry I should have documented that

**Pull request merged**
